all: lab5_2 lab52 lab5_3 lab53 lab5_4 lab54 lab5_5 lab55 lab5_6 child lab5_7 child_7 lab5_9 child1 lab5_10 child2 lab5_11 lab511

lab5_2: 
	gcc -o ./2/lab5_2 ./2/lab5_2.c
	touch mq

lab52: 
	gcc -o ./2/lab52 ./2/lab52.c

lab5_3:
	gcc -o ./3/lab5_3 ./3/lab5_3.c
	touch mq

lab53:
	gcc -o ./3/lab5_3 ./3/lab53.c

lab5_4:
	gcc -o ./4/lab5_4 ./4/lab5_4.c
	touch mq
lab54:
	gcc -o ./4/lab5_4 ./4/lab54.c
lab5_5:
	gcc -o ./5/lab5_5 ./5/lab5_5.c
	touch mq

lab55:
	gcc -o ./5/lab55 ./5/lab55.c

lab5_6:
	gcc -o ./6/lab5_6 ./6/lab5_6.c
	touch mq

child:
	gcc -o ./6/child ./6/child.c
lab5_7:
	gcc -o ./7/lab5_7 ./7/lab5_7.c
	touch mq
child_7:
	gcc -o ./7/child7 ./7/child_7.c
lab5_9:
	gcc -o ./9/lab5_9 ./9/lab5_9.c
	touch mq
child1:
	gcc -o ./9/child1 ./9/child1.c
lab5_10:
	gcc -o ./10/lab5_10 ./10/lab5_10.c
	touch mq
child2:
	gcc -o ./10/child2 ./10/child2.c

lab5_11:
	gcc -o ./11/lab5_11 ./11/lab5_11.c
	touch mq

lab511:
	gcc -o ./11/lab511 ./11/lab511.c
